(re: issue #22) Code to copy neuroimaging BIDS data from an outside directory to the main BIDS directory
htwangtw/adie_ongoingthoughts pull request #23
Opened 2021-03-15 14:34 UTC by willstrawson

BIDS fmri data is now in the main BIDS directory thanks to code inside subject_dir_assimilate/ . I've experimented with importing my own functions, hence why everything's inside one directory. Next step is to integrate my functions script with yours.

2021-03-22 10:19 UTC, htwangtw requested changes
Well done! 
Can you add `.DS_store` to .gitignore?

Currently your directory structure is still very chaotic. There seem to be lots of files duplicating themselves interms of functionality. 
I am fine with self defined function stored in `bin` for now, but I would need you to think about the following things when making the changes:

1. `bin/heudiconv` and `bin/sub_sir_assimilate` should only contain modules and functions
2. Scripts (e.g. `bin/sub_dir_assimilate/assimilate.py`) should be right under `bin`
3. Remove duplicate files.

After that we can think about tests.

2021-03-22 10:19 UTC, htwangtw commented on bin/cisc_to_adie_conversion.py
> +# Function 1 - consolidate sub- dir as string - bit redundent for now but may come in handy
Why not just include these comments as docstrings like this. Prevent description like function 1, 2, 3
[python docsting documentation](https://numpydoc.readthedocs.io/en/latest/format.html)
```python
def myfunc(var):
    """
    Doc string here
    This is a function that add 1 to integer
    """
    if type(var) == int:
        return var+1
    else:
        raise TypeError("not a integer")
```

2021-03-22 10:19 UTC, htwangtw commented on bin/cisc_to_adie_conversion.py
> +        print("CISC ID ({}) not recognized!".format(cid))
I would use `raise` for errors instead of print.

2021-03-22 10:19 UTC, htwangtw commented on bin/cisc_to_adie_conversion.py
> +            print("Directory already exists!")
Save as above

2021-03-22 10:19 UTC, htwangtw commented on bin/cisc_to_adie_conversion.py
> +    for root,dirs,files in os.walk(sub):
The reason you need to make exception for `DS_Store` is because you sued the generic walk function. Try to modify this function with `glob` and use pathlib.

2021-03-22 10:19 UTC, htwangtw commented on bin/cisc_to_adie_conversion.py
> +def newdir(newid,root):
Check python function style

2021-03-22 10:19 UTC, htwangtw commented on bin/heudiconv/run_heudiconv.py
> +def subses(sub):
Name functions more explicitly. Such as  `gen_ses_label`

2021-03-22 10:19 UTC, htwangtw commented on bin/heudiconv/run_heudiconv.py
> +def hc(sub,ses, out):
`run_heudiconv`?

2021-03-22 10:19 UTC, htwangtw commented on bin/cisc_to_adie_conversion.py
> +# -------------- RUN FUNCTIONS -------------- #
Check this repo for a very minimal case of test writing: https://github.com/htwangtw/publiccrawler
In short, you are NOT using real data for testing. What you would do here is create some empty files as test files. 
You should aim for one test for one function if possible.

2021-03-22 10:19 UTC, htwangtw commented on bin/cisc_to_adie_conversion.py
> +    # F3 - Recreate directory sturcture, using new ID names
If the functions are named more explicitly, you will be able to avoid  comments like this

2021-03-22 10:19 UTC, htwangtw commented on bin/cisc_to_adie_conversion.py
> +def subpaths(sub):
This is a pointless function....

2021-03-22 12:38 UTC, willstrawson commented
@htwangtw Hellooo

2021-03-26 12:18 UTC, willstrawson commented on bin/cisc_to_adie_conversion.py
> +# Function 1 - consolidate sub- dir as string - bit redundent for now but may come in handy
I like these docstrings :)

2021-03-26 12:18 UTC, willstrawson commented on bin/cisc_to_adie_conversion.py
> +        print("CISC ID ({}) not recognized!".format(cid))
Cool, will start using this

2021-03-26 12:22 UTC, willstrawson commented on bin/cisc_to_adie_conversion.py
> +# -------------- RUN FUNCTIONS -------------- #
Thanks I'm still keen to start writing tests so will save this repo 🥇

2021-03-26 12:28 UTC, willstrawson commented on bin/cisc_to_adie_conversion.py
> +def subpaths(sub):
Yeah true, deleted

2021-03-26 13:24 UTC, willstrawson commented on bin/heudiconv/run_heudiconv.py
> +def subses(sub):
done

2021-03-26 13:25 UTC, willstrawson commented on bin/heudiconv/run_heudiconv.py
> +def hc(sub,ses, out):
done

2021-03-26 17:14 UTC, willstrawson commented
Hey @htwangtw, I've ran the three scripts  (1. run_heudiconv.py, 2. cisc_to_adie_conservsion.py, 3. migrate_existing_subject.py) with a test case and they all work 💯 

See what you think but I'm happy to close this PR

2021-03-29 14:35 UTC, htwangtw approved these changes
I cannot find your test in this PR, although you said you have written some. 
I am happy to merge this PR without tests. If you are not written for `pytest`, I can overlook it quite easily. 

Please check the changes I make.
Also, please make sure all new files created are fitting BIDS standard.

A few things to look out for in the future
- Avoid wild card when calling functions from a module. Look up the reason yourself.
- Don't hard-code path inside a function. Anything related to the file path should be set as input variables so it can be isolated to debug and write test on it.

2021-03-29 14:35 UTC, htwangtw commented on bin/t1_and_mw_scan_descriptives.py
> +        "/research/cisc2/projects/critchley_adie/BIDS_data/participants2.tsv"
Avoid naming file like this. If this is for updating an existing file, why not over write the old file?
Output not fitting BIDS standard.

2021-03-29 14:35 UTC, htwangtw commented on adie/migrate.py
> +    base = "/research/cisc2/projects/critchley_adie/"
Don't hard-code file path in functions. Pass file path as input.

2021-03-29 14:38 UTC, merged

2021-03-29 14:43 UTC, htwangtw commented
If there's any changes to these files you want to make in the future, open new PR to update!